export const CREATE_SYSTEM_NOTIFICATION = 'CREATE_SYSTEM_NOTIFICATION'
export const DELETE_SYSTEM_NOTIFICATION = 'DELETE_SYSTEM_NOTIFICATION'

export const TOGGLE_BACK_TO_TOP_VISIBILITY = 'TOGGLE_BACK_TO_TOP_VISIBILITY'

export const USER_SET_PRELOADER_MANUAL = 'USER_SET_PRELOADER_MANUAL'

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_GET_AUTH_REQUEST = 'USER_GET_AUTH_REQUEST'
export const USER_GET_AUTH_SUCCESS = 'USER_GET_AUTH_SUCCESS'
export const USER_GET_AUTH_FAILURE = 'USER_GET_AUTH_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_TOGGLE_LOGIN_MODAL = 'USER_TOGGLE_LOGIN_MODAL'
export const USER_TOGGLE_EMAIL_CONFIRM_MODAL = 'USER_TOGGLE_EMAIL_CONFIRM_MODAL'
export const USER_TOGGLE_RESPONSIVE_SIDEBAR = 'USER_TOGGLE_RESPONSIVE_SIDEBAR'
export const USER_TOGGLE_UPDATE_REVIEW_MODAL = 'USER_TOGGLE_UPDATE_REVIEW_MODAL'
export const USER_TOGGLE_CHANGE_EMAIL_MODAL = 'USER_TOGGLE_CHANGE_EMAIL_MODAL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_ERROR = 'USER_UPDATE_USER'

export const USER_GET_ADDRESS_REQUEST = 'USER_GET_ADDRESS_REQUEST'
export const USER_GET_ADDRESS_SUCCESS = 'USER_GET_ADDRESS_SUCCESS'
export const USER_GET_ADDRESS_ERROR = 'USER_GET_ADDRESS_ERROR'

export const USER_GET_ORDERS_REQUEST = 'USER_GET_ORDERS_REQUEST'
export const USER_GET_ORDERS_SUCCESS = 'USER_GET_ORDERS_SUCCESS'
export const USER_GET_ORDERS_ERROR = 'USER_GET_ORDERS_ERROR'

export const USER_GET_ORDER_REQUEST = 'USER_GET_ORDER_REQUEST'
export const USER_GET_ORDER_SUCCESS = 'USER_GET_ORDER_SUCCESS'
export const USER_GET_ORDER_ERROR = 'USER_GET_ORDER_ERROR'

export const USER_GET_PAYMENT_METHODS_REQUEST = 'USER_GET_ADDRESS_REQUEST'
export const USER_GET_PAYMENT_METHODS_SUCCESS = 'USER_GET_ADDRESS_SUCCESS'
export const USER_GET_PAYMENT_METHODS_ERROR = 'USER_GET_ADDRESS_ERROR'

export const USER_DELETE_PAYMENT_METHOD_REQUEST = 'USER_DELETE_PAYMENT_METHOD_REQUEST'
export const USER_DELETE_PAYMENT_METHOD_SUCCESS = 'USER_DELETE_PAYMENT_METHOD_SUCCESS'
export const USER_DELETE_PAYMENT_METHOD_ERROR = 'USER_DELETE_PAYMENT_METHOD_ERROR'

export const USER_UPDATE_RESELLER_PERMITS_REQUEST = 'USER_UPDATE_RESELLER_PERMITS_REQUEST'
export const USER_UPDATE_RESELLER_PERMITS_SUCCESS = 'USER_UPDATE_RESELLER_PERMITS_SUCCESS'
export const USER_UPDATE_RESELLER_PERMITS_ERROR = 'USER_UPDATE_RESELLER_PERMITS_ERROR'

export const USER_CREATE_RESELLER_PERMITS_REQUEST = 'USER_CREATE_RESELLER_PERMITS_REQUEST'
export const USER_CREATE_RESELLER_PERMITS_SUCCESS = 'USER_CREATE_RESELLER_PERMITS_SUCCESS'
export const USER_CREATE_RESELLER_PERMITS_ERROR = 'USER_CREATE_RESELLER_PERMITS_ERROR'

export const USER_GET_RESELLER_PERMITS_REQUEST = 'USER_GET_RESELLER_PERMITS_REQUEST'
export const USER_GET_RESELLER_PERMITS_SUCCESS = 'USER_GET_RESELLER_PERMITS_SUCCESS'
export const USER_GET_RESELLER_PERMITS_ERROR = 'USER_GET_RESELLER_PERMITS_ERROR'

export const USER_DELETE_RESELLER_PERMIT_REQUEST = 'USER_DELETE_RESELLER_PERMIT_REQUEST'
export const USER_DELETE_RESELLER_PERMIT_SUCCESS = 'USER_DELETE_RESELLER_PERMIT_SUCCESS'
export const USER_DELETE_RESELLER_PERMIT_ERROR = 'USER_DELETE_RESELLER_PERMIT_ERROR'

export const USER_UPDATE_ORDER_REQUEST = 'USER_UPDATE_ORDER_REQUEST'
export const USER_UPDATE_ORDER_SUCCESS = 'USER_UPDATE_ORDER_SUCCESS'
export const USER_UPDATE_ORDER_ERROR = 'USER_UPDATE_ORDER_ERROR'

export const USER_UPDATE_ORDERS_REQUEST = 'USER_UPDATE_ORDERS_REQUEST'
export const USER_UPDATE_ORDERS_SUCCESS = 'USER_UPDATE_ORDERS_SUCCESS'
export const USER_UPDATE_ORDERS_ERROR = 'USER_UPDATE_ORDERS_ERROR'

export const USER_UPDATE_EMAIL_REQUEST = 'USER_UPDATE_EMAIL_REQUEST'
export const USER_UPDATE_EMAIL_SUCCESS = 'USER_UPDATE_EMAIL_SUCCESS'
export const USER_UPDATE_EMAIL_ERROR = 'USER_UPDATE_EMAIL_ERROR'

export const USER_CREATE_ORDER_PROCESSING_REQUEST = 'USER_CREATE_ORDER_PROCESSING_REQUEST'
export const USER_CREATE_ORDER_PROCESSING_SUCCESS = 'USER_CREATE_ORDER_PROCESSING_SUCCESS'
export const USER_CREATE_ORDER_PROCESSING_ERROR = 'USER_CREATE_ORDER_PROCESSING_ERROR'

export const USER_CREATE_INVOICE_TOKEN_REQUEST = 'USER_CREATE_INVOICE_TOKEN_REQUEST'
export const USER_CREATE_INVOICE_TOKEN_SUCCESS = 'USER_CREATE_INVOICE_TOKEN_SUCCESS'
export const USER_CREATE_INVOICE_TOKEN_ERROR = 'USER_CREATE_INVOICE_TOKEN_ERROR'

export const USER_DELETE_ORDER_REQUEST = 'USER_DELETE_ORDER_REQUEST'
export const USER_DELETE_ORDER_SUCCESS = 'USER_DELETE_ORDER_SUCCESS'
export const USER_DELETE_ORDER_ERROR = 'USER_DELETE_ORDER_ERROR'

export const USER_DELETE_ADDRESS_REQUEST = 'USER_DELETE_ADDRESS_REQUEST'
export const USER_DELETE_ADDRESS_SUCCESS = 'USER_DELETE_ADDRESS_SUCCESS'
export const USER_DELETE_ADDRESS_ERROR = 'USER_DELETE_ADDRESS_ERROR'

export const USER_SET_ADDRESS_MAIN_REQUEST = 'USER_SET_ADDRESS_MAIN_REQUEST'
export const USER_SET_ADDRESS_MAIN_SUCCESS = 'USER_SET_ADDRESS_MAIN_SUCCESS'
export const USER_SET_ADDRESS_MAIN_ERROR = 'USER_SET_ADDRESS_MAIN_ERROR'

export const USER_SAVE_ADDRESS_REQUEST = 'USER_SAVE_ADDRESS_REQUEST'
export const USER_SAVE_ADDRESS_SUCCESS = 'USER_SAVE_ADDRESS_SUCCESS'
export const USER_SAVE_ADDRESS_ERROR = 'USER_SAVE_ADDRESS_ERROR'

export const USER_CREATE_PURCHASE_REQUEST = 'USER_CREATE_PURCHASE_REQUEST'
export const USER_CREATE_PURCHASE_SUCCESS = 'USER_CREATE_PURCHASE_SUCCESS'
export const USER_CREATE_PURCHASE_ERROR = 'USER_CREATE_PURCHASE_ERROR'

export const USER_CREATE_FEEDBACK_REQUEST = 'USER_CREATE_FEEDBACK_REQUEST'
export const USER_CREATE_FEEDBACK_SUCCESS = 'USER_CREATE_FEEDBACK_SUCCESS'
export const USER_CREATE_FEEDBACK_ERROR = 'USER_CREATE_FEEDBACK_ERROR'

export const USER_CREATE_REVIEW_REQUEST = 'USER_CREATE_REVIEW_REQUEST'
export const USER_CREATE_REVIEW_SUCCESS = 'USER_CREATE_REVIEW_SUCCESS'
export const USER_CREATE_REVIEW_ERROR = 'USER_CREATE_REVIEW_ERROR'

export const USER_DELETE_REVIEW_REQUEST = 'USER_DELETE_REVIEW_REQUEST'
export const USER_DELETE_REVIEW_SUCCESS = 'USER_DELETE_REVIEW_SUCCESS'
export const USER_DELETE_REVIEW_ERROR = 'USER_CREATE_REVIEW_ERROR'

export const USER_UPDATE_REVIEW_REQUEST = 'USER_UPDATE_REVIEW_REQUEST'
export const USER_UPDATE_REVIEW_SUCCESS = 'USER_UPDATE_REVIEW_SUCCESS'
export const USER_UPDATE_REVIEW_ERROR = 'USER_UPDATE_REVIEW_ERROR'

export const USER_FETCH_BRAINTREE_TOKEN_REQUEST = 'USER_FETCH_BRAINTREE_TOKEN_REQUEST'
export const USER_FETCH_BRAINTREE_TOKEN_SUCCESS = 'USER_FETCH_BRAINTREE_TOKEN_SUCCESS'
export const USER_FETCH_BRAINTREE_TOKEN_ERROR = 'USER_FETCH_BRAINTREE_TOKEN_ERROR'

export const USER_UPDATE_PENDING_COUNTER = 'USER_UPDATE_PENDING_COUNTER'

export const WAIT_LIST_FETCH_REQUEST = 'WAIT_LIST_FETCH_REQUEST'
export const WAIT_LIST_FETCH_SUCCESS = 'WAIT_LIST_FETCH_SUCCESS'
export const WAIT_LIST_FETCH_ERROR = 'WAIT_LIST_FETCH_ERROR'

export const WAIT_LIST_CREATE_PRODUCT_REQUEST = 'WAIT_LIST_CREATE_PRODUCT_REQUEST'
export const WAIT_LIST_CREATE_PRODUCT_SUCCESS = 'WAIT_LIST_CREATE_PRODUCT_SUCCESS'
export const WAIT_LIST_CREATE_PRODUCT_ERROR = 'WAIT_LIST_CREATE_PRODUCT_ERROR'

export const WAIT_LIST_DELETE_PRODUCT_REQUEST = 'WAIT_LIST_DELETE_PRODUCT_REQUEST'
export const WAIT_LIST_DELETE_PRODUCT_SUCCESS = 'WAIT_LIST_DELETE_PRODUCT_SUCCESS'
export const WAIT_LIST_DELETE_PRODUCT_ERROR = 'WAIT_LIST_DELETE_PRODUCT_ERROR'

export const WAIT_LIST_UPDATE_FROM_STORAGE = 'WAIT_LIST_UPDATE_FROM_STORAGE'
export const WAIT_LIST_CLEAR = 'WAIT_LIST_CLEAR'
export const WAIT_LIST_SET_TEMPORARY_PRODUCT = 'WAIT_LIST_SET_TEMPORARY_PRODUCT'

export const SEARCH_TOGGLE_MODAL = 'SEARCH_TOGGLE_MODAL'

export const SEARCH_GET_REQUEST = 'SEARCH_GET_REQUEST'
export const SEARCH_GET_SUCCESS = 'SEARCH_GET_SUCCESS'
export const SEARCH_GET_ERROR = 'SEARCH_GET_ERROR'

export const SEARCH_SET_YEAR = 'SEARCH_SET_YEAR'
export const SEARCH_SET_BRAND = 'SEARCH_SET_BRAND'
export const SEARCH_SET_MODEL = 'SEARCH_SET_MODEL'
export const SEARCH_CLEAR_MODEL = 'SEARCH_CLEAR_MODEL'

export const SEARCH_SUBMIT_REQUEST = 'SEARCH_SUBMIT_REQUEST'
export const SEARCH_SUBMIT_SUCCESS = 'SEARCH_SUBMIT_SUCCESS'
export const SEARCH_SUBMIT_ERROR = 'SEARCH_SUBMIT_ERROR'

export const USER_SUBMIT_EMAIL_REQUEST = 'USER_SUBMIT_EMAIL_REQUEST'
export const USER_SUBMIT_EMAIL_SUCCESS = 'USER_SUBMIT_EMAIL_SUCCESS'
export const USER_SUBMIT_EMAIL_ERROR = 'USER_SUBMIT_EMAIL_ERROR'

export const USER_EMAIL_VERIFIED_SUCCESS = 'USER_EMAIL_VERIFIED_SUCCESS'

export const USER_RESET_PASSWORD_VALIDATION_REQUEST = 'USER_RESET_PASSWORD_VALIDATION_REQUEST'
export const USER_RESET_PASSWORD_VALIDATION_SUCCESS = 'USER_RESET_PASSWORD_VALIDATION_SUCCESS'
export const USER_RESET_PASSWORD_VALIDATION_ERROR = 'USER_RESET_PASSWORD_VALIDATION_ERROR'

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST'
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS'
export const USER_RESET_PASSWORD_ERROR = 'USER_RESET_PASSWORD_ERROR'

export const PRODUCTS_TOGGLE_CART_MODAL = 'PRODUCTS_TOGGLE_CART_MODAL'
export const PRODUCTS_SET_MODAL_PRODUCT_ID = 'PRODUCTS_SET_MODAL_PRODUCT_ID'
export const PRODUCTS_SET_PRODUCT_VIEW = 'PRODUCTS_SET_PRODUCT_VIEW'
export const PRODUCTS_SET_DEALER_VIEW = 'PRODUCTS_SET_DEALER_VIEW'

export const PRODUCTS_GET_SECTIONS_REQUEST = 'PRODUCTS_GET_SECTIONS_REQUEST'
export const PRODUCTS_GET_SECTIONS_SUCCESS = 'PRODUCTS_GET_SECTIONS_SUCCESS'
export const PRODUCTS_GET_SECTIONS_ERROR = 'PRODUCTS_GET_SECTIONS_ERROR'

export const PRODUCTS_GET_SECTION_REQUEST = 'PRODUCTS_GET_SECTION_REQUEST'
export const PRODUCTS_GET_SECTION_SUCCESS = 'PRODUCTS_GET_SECTION_SUCCESS'
export const PRODUCTS_GET_SECTION_ERROR = 'PRODUCTS_GET_SECTION_ERROR'

export const PRODUCTS_GET_CATEGORY_REQUEST = 'PRODUCTS_GET_CATEGORY_REQUEST'
export const PRODUCTS_GET_CATEGORY_SUCCESS = 'PRODUCTS_GET_CATEGORY_SUCCESS'
export const PRODUCTS_GET_CATEGORY_ERROR = 'PRODUCTS_GET_CATEGORY_ERROR'

export const PRODUCTS_GET_BRANDS_REQUEST = 'PRODUCTS_GET_BRANDS_REQUEST'
export const PRODUCTS_GET_BRANDS_SUCCESS = 'PRODUCTS_GET_BRANDS_SUCCESS'
export const PRODUCTS_GET_BRANDS_ERROR = 'PRODUCTS_GET_BRANDS_ERROR'

export const PRODUCTS_GET_VEHICLE_REQUEST = 'PRODUCTS_GET_VEHICLE_REQUEST'
export const PRODUCTS_GET_VEHICLE_SUCCESS = 'PRODUCTS_GET_VEHICLE_SUCCESS'
export const PRODUCTS_GET_VEHICLE_ERROR = 'PRODUCTS_GET_VEHICLE_ERROR'

export const PRODUCTS_GET_REQUEST = 'PRODUCTS_GET_REQUEST'
export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS'
export const PRODUCTS_GET_ERROR = 'PRODUCTS_GET_ERROR'

export const PRODUCTS_GET_HOMEPAGE_BANNERS_REQUEST = 'PRODUCTS_GET_HOMEPAGE_BANNERS_REQUEST'
export const PRODUCTS_GET_HOMEPAGE_BANNERS_SUCCESS = 'PRODUCTS_GET_HOMEPAGE_BANNERS_SUCCESS'
export const PRODUCTS_GET_HOMEPAGE_BANNERS_ERROR = 'PRODUCTS_GET_HOMEPAGE_BANNERS_ERROR'

export const PRODUCTS_GET_SINGLE_REQUEST = 'PRODUCTS_GET_SINGLE_REQUEST'
export const PRODUCTS_GET_SINGLE_SUCCESS = 'PRODUCTS_GET_SINGLE_SUCCESS'
export const PRODUCTS_GET_SINGLE_ERROR = 'PRODUCTS_GET_SINGLE_ERROR'

export const PRODUCTS_GET_FILTERS_REQUEST = 'PRODUCTS_GET_FILTERS_REQUEST'
export const PRODUCTS_GET_FILTERS_SUCCESS = 'PRODUCTS_GET_FILTERS_SUCCESS'
export const PRODUCTS_GET_FILTERS_ERROR = 'PRODUCTS_GET_FILTERS_ERROR'

export const PRODUCTS_SET_FILTERS_REQUEST = 'PRODUCTS_SET_FILTERS_REQUEST'
export const PRODUCTS_SET_FILTERS_SUCCESS = 'PRODUCTS_SET_FILTERS_SUCCESS'
export const PRODUCTS_SET_FILTERS_ERROR = 'PRODUCTS_SET_FILTERS_ERROR'

export const PRODUCTS_GET_DEALER_INFO_REQUEST = 'PRODUCTS_GET_DEALER_INFO_REQUEST'
export const PRODUCTS_GET_DEALER_INFO_SUCCESS = 'PRODUCTS_GET_DEALER_INFO_SUCCESS'
export const PRODUCTS_GET_DEALER_INFO_ERROR = 'PRODUCTS_GET_DEALER_INFO_ERROR'

export const PRODUCTS_GET_DEALER_FILTERS_REQUEST = 'PRODUCTS_GET_DEALER_FILTERS_REQUEST'
export const PRODUCTS_GET_DEALER_FILTERS_SUCCESS = 'PRODUCTS_GET_DEALER_FILTERS_SUCCESS'
export const PRODUCTS_GET_DEALER_FILTERS_ERROR = 'PRODUCTS_GET_DEALER_FILTERS_ERROR'

export const PRODUCTS_GET_DEALER_SECTIONS_REQUEST = 'PRODUCTS_GET_DEALER_SECTIONS_REQUEST'
export const PRODUCTS_GET_DEALER_SECTIONS_SUCCESS = 'PRODUCTS_GET_DEALER_SECTIONS_SUCCESS'
export const PRODUCTS_GET_DEALER_SECTIONS_ERROR = 'PRODUCTS_GET_DEALER_SECTIONS_ERROR'

export const PRODUCTS_GET_VEHICLE_SECTIONS_REQUEST = 'PRODUCTS_GET_VEHICLE_SECTIONS_REQUEST'
export const PRODUCTS_GET_VEHICLE_SECTIONS_SUCCESS = 'PRODUCTS_GET_VEHICLE_SECTIONS_SUCCESS'
export const PRODUCTS_GET_VEHICLE_SECTIONS_ERROR = 'PRODUCTS_GET_VEHICLE_SECTIONS_ERROR'

export const PRODUCTS_GET_RELATED_PRODUCTS_REQUEST = 'PRODUCTS_GET_RELATED_PRODUCTS_REQUEST'
export const PRODUCTS_GET_RELATED_PRODUCTS_SUCCESS = 'PRODUCTS_GET_RELATED_PRODUCTS_SUCCESS'
export const PRODUCTS_GET_RELATED_PRODUCTS_ERROR = 'PRODUCTS_GET_RELATED_PRODUCTS_ERROR'

export const PRODUCTS_GET_BESTSELLERS_PRODUCTS_REQUEST = 'PRODUCTS_GET_BESTSELLERS_PRODUCTS_REQUEST'
export const PRODUCTS_GET_BESTSELLERS_PRODUCTS_SUCCESS = 'PRODUCTS_GET_BESTSELLERS_PRODUCTS_SUCCESS'
export const PRODUCTS_GET_BESTSELLERS_PRODUCTS_ERROR = 'PRODUCTS_GET_BESTSELLERS_PRODUCTS_ERROR'

export const PRODUCTS_GET_FEATURED_PRODUCTS_REQUEST = 'PRODUCTS_GET_FEATURED_PRODUCTS_REQUEST'
export const PRODUCTS_GET_FEATURED_PRODUCTS_SUCCESS = 'PRODUCTS_GET_FEATURED_PRODUCTS_SUCCESS'
export const PRODUCTS_GET_FEATURED_PRODUCTS_ERROR = 'PRODUCTS_GET_FEATURED_PRODUCTS_ERROR'

export const PRODUCTS_GET_PURCHASED_PRODUCTS_REQUEST = 'PRODUCTS_GET_PURCHASED_PRODUCTS_REQUEST'
export const PRODUCTS_GET_PURCHASED_PRODUCTS_SUCCESS = 'PRODUCTS_GET_PURCHASED_PRODUCTS_SUCCESS'
export const PRODUCTS_GET_PURCHASED_PRODUCTS_ERROR = 'PRODUCTS_GET_PURCHASED_PRODUCTS_ERROR'

export const PRODUCTS_GET_REVIEWS_REQUEST = 'PRODUCTS_GET_REVIEWS_REQUEST'
export const PRODUCTS_GET_REVIEWS_SUCCESS = 'PRODUCTS_GET_REVIEWS_SUCCESS'
export const PRODUCTS_GET_REVIEWS_ERROR = 'PRODUCTS_GET_REVIEWS_ERROR'

export const PRODUCTS_GET_VIEWED_REQUERST = 'PRODUCTS_GET_VIEWED_REQUERST'
export const PRODUCTS_GET_VIEWED_SUCCESS = 'PRODUCTS_GET_VIEWED_SUCCESS'
export const PRODUCTS_GET_VIEWED_ERROR = 'PRODUCTS_GET_VIEWED_ERROR'

export const PRODUCTS_CREATE_VIEWED_REQUERST = 'PRODUCTS_CREATE_VIEWED_REQUERST'
export const PRODUCTS_CREATE_VIEWED_SUCCESS = 'PRODUCTS_CREATE_VIEWED_SUCCESS'
export const PRODUCTS_CREATE_VIEWED_ERROR = 'PRODUCTS_CREATE_VIEWED_ERROR'

export const PRODUCTS_DELETE_VIEWED_REQUERST = 'PRODUCTS_DELETE_VIEWED_REQUERST'
export const PRODUCTS_DELETE_VIEWED_SUCCESS = 'PRODUCTS_DELETE_VIEWED_SUCCESS'
export const PRODUCTS_DELETE_VIEWED_ERROR = 'PRODUCTS_DELETE_VIEWED_ERROR'

export const PRODUCTS_DELETE_ALL_VIEWED_REQUERST = 'PRODUCTS_DELETE_ALL_VIEWED_REQUERST'
export const PRODUCTS_DELETE_ALL_VIEWED_SUCCESS = 'PRODUCTS_DELETE_ALL_VIEWED_SUCCESS'
export const PRODUCTS_DELETE_ALL_VIEWED_ERROR = 'PRODUCTS_DELETE_ALL_VIEWED_ERROR'

export const CART_CREATE_REQUEST = 'CART_CREATE_REQUEST'
export const CART_CREATE_WAREHOUSE = 'CART_CREATE_SUCCESS'

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST'
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS'

export const CART_SET_TOTAL_PRICE = 'CART_SET_TOTAL_PRICE'
export const CART_SET_TOTAL_QUANTITY = 'CART_SET_TOTAL_QUANTITY'
export const CART_SET_TOTAL_AMOUNT = 'CART_SET_TOTAL_AMOUNT'

export const CART_SET_COUNTERS = 'CART_SET_COUNTERS'

export const CART_DELETE_ITEM = 'CART_DELETE_ITEM'
export const CART_CREATE_ITEM = 'CART_CREATE_ITEM'

export const CART_DELETE_WAREHOUSE_REQUEST = 'CART_DELETE_WAREHOUSE'
export const CART_DELETE_WAREHOUSE_SUCESS = 'CART_DELETE_WAREHOUSE_SUCESS'
export const CART_DELETE_WAREHOUSE_ERROR = 'CART_DELETE_WAREHOUSE_ERROR'

export const CART_DELETE_ALL_REQUEST = 'CART_DELETE_ALL_REQUEST'
export const CART_DELETE_ALL_SUCESS = 'CART_DELETE_ALL_SUCESS'
export const CART_DELETE_ALL_ERROR = 'CART_DELETE_ALL_ERROR'

export const CART_GET_SERVER_REQUEST = 'CART_GET_SERVER_REQUEST'
export const CART_GET_SERVER_SUCCESS = 'CART_GET_SERVER_SUCCESS'
export const CART_GET_SERVER_ERROR = 'CART_GET_SERVER_ERROR'

export const CART_DELETE_LOCAL = 'CART_DELETE_LOCAL'

export const CART_VALIDATION_REQUEST = 'CART_VALIDATION_REQUEST'
export const CART_VALIDATION_SUCCESS = 'CART_VALIDATION_SUCCESS'
export const CART_VALIDATION_ERROR = 'CART_VALIDATION_ERROR'

export const CART_UPDATE_FROM_STORAGE = 'CART_UPDATE_FROM_STORAGE'

export const CART_UPDATE_AVAILABLE_QUANTITY_SUCCESS = 'CART_UPDATE_AVAILABLE_QUANTITY_SUCCESS'
export const CART_UPDATE_AVAILABLE_QUANTITY_ERROR = 'CART_UPDATE_AVAILABLE_QUANTITY_ERROR'

export const PRODUCTS_GET_WAREHOUSE_REQUERST = 'PRODUCTS_GET_WAREHOUSE_REQUERST'
export const PRODUCTS_GET_WAREHOUSE_SUCCESS = 'PRODUCTS_GET_WAREHOUSE_SUCCESS'
export const PRODUCTS_GET_WAREHOUSE_ERROR = 'PRODUCTS_GET_WAREHOUSE_ERROR'

export const PRODUCTS_GET_LIST_WAREHOUSES_REQUERST = 'PRODUCTS_GET_LIST_WAREHOUSES_REQUERST'
export const PRODUCTS_GET_LIST_WAREHOUSES_SUCCESS = 'PRODUCTS_GET_LIST_WAREHOUSES_SUCCESS'
export const PRODUCTS_GET_LIST_WAREHOUSES_ERROR = 'PRODUCTS_GET_LIST_WAREHOUSES_ERROR'
